version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_AWS_REGION=${VITE_AWS_REGION}
        - VITE_AWS_USER_POOL_ID=${VITE_AWS_USER_POOL_ID}
        - VITE_AWS_USER_POOL_CLIENT_ID=${VITE_AWS_USER_POOL_CLIENT_ID}
        - VITE_DOCUMENTDB_URI=${VITE_DOCUMENTDB_URI}
        - VITE_DOCUMENTDB_DBNAME=${VITE_DOCUMENTDB_DBNAME}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - "80:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
